//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Taxi", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Taxi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceKM {
            get {
                return this.PriceKMField;
            }
            set {
                if ((this.PriceKMField.Equals(value) != true)) {
                    this.PriceKMField = value;
                    this.RaisePropertyChanged("PriceKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassOfCarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForPassagersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNumberOfPassagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.Taxi[] TaxiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VantashopidyomKGField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassOfCar {
            get {
                return this.ClassOfCarField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassOfCarField, value) != true)) {
                    this.ClassOfCarField = value;
                    this.RaisePropertyChanged("ClassOfCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForPassagers {
            get {
                return this.ForPassagersField;
            }
            set {
                if ((this.ForPassagersField.Equals(value) != true)) {
                    this.ForPassagersField = value;
                    this.RaisePropertyChanged("ForPassagers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberOfPassager {
            get {
                return this.MaxNumberOfPassagerField;
            }
            set {
                if ((this.MaxNumberOfPassagerField.Equals(value) != true)) {
                    this.MaxNumberOfPassagerField = value;
                    this.RaisePropertyChanged("MaxNumberOfPassager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.Taxi[] Taxies {
            get {
                return this.TaxiesField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxiesField, value) != true)) {
                    this.TaxiesField = value;
                    this.RaisePropertyChanged("Taxies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VantashopidyomKG {
            get {
                return this.VantashopidyomKGField;
            }
            set {
                if ((this.VantashopidyomKGField.Equals(value) != true)) {
                    this.VantashopidyomKGField = value;
                    this.RaisePropertyChanged("VantashopidyomKG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateOfOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.Taxi TaxiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coment {
            get {
                return this.ComentField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentField, value) != true)) {
                    this.ComentField = value;
                    this.RaisePropertyChanged("Coment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateOfOrder {
            get {
                return this.StateOfOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.StateOfOrderField, value) != true)) {
                    this.StateOfOrderField = value;
                    this.RaisePropertyChanged("StateOfOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.Taxi Taxi {
            get {
                return this.TaxiField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxiField, value) != true)) {
                    this.TaxiField = value;
                    this.RaisePropertyChanged("Taxi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPerson")]
    public interface IPerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetTaxies", ReplyAction="http://tempuri.org/IPerson/GetTaxiesResponse")]
        ConsoleApplication1.ServiceReference1.Taxi[] GetTaxies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetTaxies", ReplyAction="http://tempuri.org/IPerson/GetTaxiesResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Taxi[]> GetTaxiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/MyOrders", ReplyAction="http://tempuri.org/IPerson/MyOrdersResponse")]
        ConsoleApplication1.ServiceReference1.Order[] MyOrders(ConsoleApplication1.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/MyOrders", ReplyAction="http://tempuri.org/IPerson/MyOrdersResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Order[]> MyOrdersAsync(ConsoleApplication1.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/AllCars", ReplyAction="http://tempuri.org/IPerson/AllCarsResponse")]
        ConsoleApplication1.ServiceReference1.Car[] AllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/AllCars", ReplyAction="http://tempuri.org/IPerson/AllCarsResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Car[]> AllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/MakeOrder", ReplyAction="http://tempuri.org/IPerson/MakeOrderResponse")]
        string MakeOrder(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi t, string from, string to, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/MakeOrder", ReplyAction="http://tempuri.org/IPerson/MakeOrderResponse")]
        System.Threading.Tasks.Task<string> MakeOrderAsync(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi t, string from, string to, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/ChangeStateOfOrder", ReplyAction="http://tempuri.org/IPerson/ChangeStateOfOrderResponse")]
        string ChangeStateOfOrder(ConsoleApplication1.ServiceReference1.Order order, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/ChangeStateOfOrder", ReplyAction="http://tempuri.org/IPerson/ChangeStateOfOrderResponse")]
        System.Threading.Tasks.Task<string> ChangeStateOfOrderAsync(ConsoleApplication1.ServiceReference1.Order order, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/CreateNewPerson", ReplyAction="http://tempuri.org/IPerson/CreateNewPersonResponse")]
        string CreateNewPerson(string FirstName, string SecondName, string Email, string Password, byte[] img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/CreateNewPerson", ReplyAction="http://tempuri.org/IPerson/CreateNewPersonResponse")]
        System.Threading.Tasks.Task<string> CreateNewPersonAsync(string FirstName, string SecondName, string Email, string Password, byte[] img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/Authoriz", ReplyAction="http://tempuri.org/IPerson/AuthorizResponse")]
        bool Authoriz(string email, string passw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/Authoriz", ReplyAction="http://tempuri.org/IPerson/AuthorizResponse")]
        System.Threading.Tasks.Task<bool> AuthorizAsync(string email, string passw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/WriteEmail", ReplyAction="http://tempuri.org/IPerson/WriteEmailResponse")]
        string WriteEmail(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi taxi, string Thema, string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/WriteEmail", ReplyAction="http://tempuri.org/IPerson/WriteEmailResponse")]
        System.Threading.Tasks.Task<string> WriteEmailAsync(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi taxi, string Thema, string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/ForgetPassword", ReplyAction="http://tempuri.org/IPerson/ForgetPasswordResponse")]
        string ForgetPassword(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/ForgetPassword", ReplyAction="http://tempuri.org/IPerson/ForgetPasswordResponse")]
        System.Threading.Tasks.Task<string> ForgetPasswordAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/SingOut", ReplyAction="http://tempuri.org/IPerson/SingOutResponse")]
        void SingOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/SingOut", ReplyAction="http://tempuri.org/IPerson/SingOutResponse")]
        System.Threading.Tasks.Task SingOutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonChannel : ConsoleApplication1.ServiceReference1.IPerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IPerson>, ConsoleApplication1.ServiceReference1.IPerson {
        
        public PersonClient() {
        }
        
        public PersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.ServiceReference1.Taxi[] GetTaxies() {
            return base.Channel.GetTaxies();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Taxi[]> GetTaxiesAsync() {
            return base.Channel.GetTaxiesAsync();
        }
        
        public ConsoleApplication1.ServiceReference1.Order[] MyOrders(ConsoleApplication1.ServiceReference1.Person p) {
            return base.Channel.MyOrders(p);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Order[]> MyOrdersAsync(ConsoleApplication1.ServiceReference1.Person p) {
            return base.Channel.MyOrdersAsync(p);
        }
        
        public ConsoleApplication1.ServiceReference1.Car[] AllCars() {
            return base.Channel.AllCars();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Car[]> AllCarsAsync() {
            return base.Channel.AllCarsAsync();
        }
        
        public string MakeOrder(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi t, string from, string to, string comment) {
            return base.Channel.MakeOrder(person, t, from, to, comment);
        }
        
        public System.Threading.Tasks.Task<string> MakeOrderAsync(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi t, string from, string to, string comment) {
            return base.Channel.MakeOrderAsync(person, t, from, to, comment);
        }
        
        public string ChangeStateOfOrder(ConsoleApplication1.ServiceReference1.Order order, string state) {
            return base.Channel.ChangeStateOfOrder(order, state);
        }
        
        public System.Threading.Tasks.Task<string> ChangeStateOfOrderAsync(ConsoleApplication1.ServiceReference1.Order order, string state) {
            return base.Channel.ChangeStateOfOrderAsync(order, state);
        }
        
        public string CreateNewPerson(string FirstName, string SecondName, string Email, string Password, byte[] img) {
            return base.Channel.CreateNewPerson(FirstName, SecondName, Email, Password, img);
        }
        
        public System.Threading.Tasks.Task<string> CreateNewPersonAsync(string FirstName, string SecondName, string Email, string Password, byte[] img) {
            return base.Channel.CreateNewPersonAsync(FirstName, SecondName, Email, Password, img);
        }
        
        public bool Authoriz(string email, string passw) {
            return base.Channel.Authoriz(email, passw);
        }
        
        public System.Threading.Tasks.Task<bool> AuthorizAsync(string email, string passw) {
            return base.Channel.AuthorizAsync(email, passw);
        }
        
        public string WriteEmail(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi taxi, string Thema, string Message) {
            return base.Channel.WriteEmail(person, taxi, Thema, Message);
        }
        
        public System.Threading.Tasks.Task<string> WriteEmailAsync(ConsoleApplication1.ServiceReference1.Person person, ConsoleApplication1.ServiceReference1.Taxi taxi, string Thema, string Message) {
            return base.Channel.WriteEmailAsync(person, taxi, Thema, Message);
        }
        
        public string ForgetPassword(string email) {
            return base.Channel.ForgetPassword(email);
        }
        
        public System.Threading.Tasks.Task<string> ForgetPasswordAsync(string email) {
            return base.Channel.ForgetPasswordAsync(email);
        }
        
        public void SingOut() {
            base.Channel.SingOut();
        }
        
        public System.Threading.Tasks.Task SingOutAsync() {
            return base.Channel.SingOutAsync();
        }
    }
}
